version: '3.9'

services:
  client:
    container_name: todo-client
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 3000
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - todo-network  

networks:
  todo-network:
    driver: bridge
